version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 33060:3306
    volumes:
      - /mysql_docker:/var/lib/mysql
    networks:
      - lamp-network
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: viajes
      MYSQL_USER: user
      MYSQL_PASSWORD: password1234

  php-apache:
    image: php:7.4-apache
    ports:
      - 8080:80
    volumes:
      - /html_docker:/var/www/html
    depends_on:
      - mysql
    networks:
      - lamp-network

networks:
  lamp-network:
